#bind: 0.0.0.0
#port: 22211

# Crypto
publicKey: "./keys/server.pub"
privateKey: "./keys/server.key"

# Misc.
#serverIP: 0.0.0.0
#echoIpv4Server: "https://ipv4.ip.openspa.org"
#echoIpv6Server: "https://ipv6.ip.openspa.org"

# Extension Scripts (ES)
# Checkout: https://github.com/greenstatic/openspa-extension-scripts
# to download and configure various available extension scripts.
extensionScripts:
  # Used to retrieve the users public key
  userDirectoryService: "./es/user_directory_service.py"

  # Used to determine if the user is authorized to
  # access the service by returning (stdout) the
  # number of seconds to allow access. If the script
  # returns 0, we will not send a response packet.
  authorization: "./es/authorization.py"

  # Used to add a rule to the firewall.
  ruleAdd: "./es/rule_add.py"

  # Used to remove a rule from the firewall.
  ruleRemove: "./es/rule_remove.py"
